### ISSUE TITLE
[BUG]: NPE

### ISSUE THREAD

**Issue by glebsts** [cortiz/ssl-toolbox#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

![image](https://github.com/user-attachments/assets/4ec56171-e81a-48ce-8345-d9253e520719)
```
com.intellij.diagnostic.PluginException: null [Plugin: com.jmpeax.ssltoolbox]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.getProviderIfApplicable(FileEditorProviderManagerImpl.kt:208)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.access$getProviderIfApplicable(FileEditorProviderManagerImpl.kt:1)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1$2.invokeSuspend(FileEditorProviderManagerImpl.kt:107)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1$2.invoke(FileEditorProviderManagerImpl.kt)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1$2.invoke(FileEditorProviderManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:46)
	at kotlinx.coroutines.TimeoutKt.withTimeout-KLykuaI(Timeout.kt:74)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at com.jmpeax.ssltoolbox.pem.PEMFileEditorProvider.accept(PEMFileEditorProvider.java:17)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.checkProvider(FileEditorProviderManagerImpl.kt:217)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.access$checkProvider(FileEditorProviderManagerImpl.kt:1)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt$getProviderIfApplicable$3.invoke(FileEditorProviderManagerImpl.kt:189)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt$getProviderIfApplicable$3.invoke(FileEditorProviderManagerImpl.kt:188)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:310)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:40)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.getProviderIfApplicable(FileEditorProviderManagerImpl.kt:188)
	... 15 more
```

### Steps To Reproduce

I have plugin 0.1.4 installed, I used it successfully with one project, now I open another project which does not have any keystores, and is not even a real project (empty repo with readme). Happens regularly, I actually quite often disable plugin because of this error, and enable it when I need to inspect keystores. Then I forget to disable it back, and get same error...

Also, in this bug reporting form version selector there is only v 0.1.0 available, but it is about 0.1.4

### Which version of the app are you using?

0.1.4

**Comment by timmydog** [comment]
I have a fix for this issue - just a check for null, but it fixed the issue for me:
```
Index: src/main/java/com/jmpeax/ssltoolbox/pem/PEMFileEditorProvider.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/com/jmpeax/ssltoolbox/pem/PEMFileEditorProvider.java b/src/main/java/com/jmpeax/ssltoolbox/pem/PEMFileEditorProvider.java
--- a/src/main/java/com/jmpeax/ssltoolbox/pem/PEMFileEditorProvider.java	(revision 6d17d73e39790e9c6083f2eb0fce9dc2a0b02636)
+++ b/src/main/java/com/jmpeax/ssltoolbox/pem/PEMFileEditorProvider.java	(date 1741002997298)
@@ -14,7 +14,13 @@
 public class PEMFileEditorProvider implements FileEditorProvider {
     @Override
     public boolean accept(@NotNull Project project, @NotNull VirtualFile file) {
-        return switch (Objects.requireNonNull(file.getExtension()).toLowerCase()) {
+        String fileExtension = file.getExtension();
+
+        if(fileExtension == null) {
+            return false;
+        }
+
+        return switch (Objects.requireNonNull(fileExtension).toLowerCase()) {
             case "pem", "cer", "der", "crt", "ca-bundle", "p7b", "p7c", "cert" -> true;
             default -> false;
         };

```

**Comment by cortiz** [comment]
Thank you 
I'll add this fix and, hopefully, release it with a couple of new features by the end of this week.
